### ISSUE TITLE
label not 	 support Chinese

### ISSUE THREAD

**Issue by childeYin** [endroid/QrCode#102]
I set $label = '有限公司', but I got  [][][][] in qrcode; $label is encoding UTF-8

**Comment by endroid** [comment]
Hi @childeYin I got this question earlier and this can be solved by using a font Noto mentioned in https://github.com/endroid/QrCode/issues/51. I now added the font to the repository and set it as default. It is a large fonts but I think it is good to increase compatibility.

So please try version 2.0.11 and see if your problem is solved.
