### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by surjit** [endroid/QrCode#107]
Built-in validation reader read "" instead of "d2llMS9uU01BVmlvalM2YU9BUFBPTTdQMmJabHpqdndt". Adjust your parameters to increase readability or disable built-in validation.

I trying with json data ?(uuid + other in array)

**Comment by endroid** [comment]
Hi @surjit, please provide your code so I can try to reproduce the issue. Thank you.

**Comment by sylvat** [comment]
I have the same issue. I guess the encode string is too long.

ValidationException in PngWriter.php line 49:
Built-in validation reader read "" instead of "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111".
Adjust your parameters to increase readability or disable built-in validation.

**Comment by endroid** [comment]
Hi @sylvat, I was able to generate a valid QR code for the string you mentioned so the input length does not appear to be the issue. Long strings result in many blocks so maybe increasing the image size or error correction level solves the issue.

If it is something else, please create a failing test case so I can reproduce the issue.

**Comment by fecou** [comment]
Hi. I @endroid. I have the same problem. it seems my string is too long. It works perfectly if I reduce it to the half. But as I have a hash in the url I want to write, I cannot make it shorter. 
Is there a way to authorize larger string ?

**Comment by endroid** [comment]
Hi @fecou please try the following.

1. Increase the size and error correction level and see if the problem persists
2. Try to read the QR code using another reader (i.e. Android Barcode Scanner).

If the problem still persists please provide a code example so I can reproduce the issue.

**Comment by fecou** [comment]
Thank you @endroid  for your quick response.
Here is my code
`
$qrCode = $this->get('endroid.qrcode.factory')->create("localhost/preinscription/1/f3a450d9545685097a486e7446730d9f/");
        $qrCode
            ->setSize(600)
            ->setMargin(10)
            ->setEncoding('UTF-8')
            ->setErrorCorrectionLevel(ErrorCorrectionLevel::HIGH)
            ->setForegroundColor(['r' => 0, 'g' => 0, 'b' => 0])
            ->setBackgroundColor(['r' => 255, 'g' => 255, 'b' => 255])
            ->setValidateResult(true) 
        ;

        // Save it to a file (guesses writer by file extension)
        $QRCodeFilePath = "my/path/...;
        $qrCode->writeFile($QRCodeFilePath);
        header('Content-Type: '.$qrCode->getContentType(PngWriter::class));
        echo $qrCode->writeString(PngWriter::class);
$response = new Response(
            $qrCode->writeString(PngWriter::class),
            Response::HTTP_OK,
            ['Content-Type' => $qrCode->getContentType(PngWriter::class)])
        ;

        return $response;
`

and the error given is : 
 request.CRITICAL: Uncaught PHP Exception Endroid\QrCode\Exception\ValidationException: "Built-in validation reader read "" instead of "localhost/preinscription/1/f3a450d9545685097a486e7446730d9f/".                      Adjust your parameters to increase readability or disable built-in validation." at /home/fe/web/sf/vendor/endroid/qrcode/src/Writer/PngWriter.php line 49 {"exception":"[object] (Endroid\\QrCode\\Exception\\ValidationException(code: 0): Built-in validation reader read \"\" instead of \"localhost/preinscription/1/f3a450d9545685097a486e7446730d9f/\".\n                     Adjust your parameters to increase readability or disable built-in validation. at /home/fe/web/sfUIAD/vendor/endroid/qrcode/src/Writer/PngWriter.php:49)"} []

Tell me if you need more information. Thanks again.

**Comment by endroid** [comment]
You're right. When you set the error correction level to low however it seems to work. This appears to be an issue in the underlying generator library so I created an issue for you there.

https://github.com/Bacon/BaconQrCode/issues/28

**Comment by fecou** [comment]
Ok, thanks a lot. If I do what you say, it works !

**Comment by fecou** [comment]
Hello @endroid,
Actually I still have a problem. I made the string to qrcode shorter so that I almost never have problem. But I don't know why, if I put "3;711;1e18da5f2033c7793c1d94dbedc44ebf", it results in an error (Built-in validation reader read "" instead of "3;711;1e18da5f2033c7793c1d94dbedc44ebf"), but if I put  "3;706;9e153d81fdbbd98384c8ea65f384f5e4", it works. I have like 10% errors. It's very strange as the chain is still very short and has always the same length...

**Comment by endroid** [comment]
Hi @fecou you are correct. When I use the strings you provided I get the same results. When I check the QR codes with my Android barcode scanner this scanner also clearly has more difficulty reading the first than the second so it looks like this one is really harder. Unfortunately I can not see if this is caused by the writer https://github.com/Bacon/BaconQrCode or the validator https://github.com/khanamiryan/php-qrcode-detector-decoder so I don't know where you could best post your question.

When I set my error correction level to "high" both the Android reader and the validation reader correctly read the QR code. Have you tried that? Maybe you can use that setting for now until the issue is solved in either of the libraries.

**Comment by phi1618033** [comment]
I encountered the same issue. I went around it with `obj->setErrorCorrectionLevel(ErrorCorrectionLevel::LOW);`. Looking forward to a solved issue. @endroid, thank you for this great library.
