### ISSUE TITLE
Feature request: QR codes types.

### ISSUE THREAD

**Issue by thatside** [endroid/QrCode#30]
It would be great to have a possibility to change QR types like url or other. I think, most people use QR for links, and scanners do differ URLs and text.

**Comment by lewison** [comment]
this lib is to create qrcode image, How to do with the text in qrcode is not it's job. Scanner do that.

**Comment by thatside** [comment]
I've tried to create different types on qr codes here. You can see different types of QR on the left hand, first two are "url" and "text". If you create these two codes with the same content, you'll see they are different.

**Comment by quantumpacket** [comment]
As far as I can tell, these different "types" are just using different URL schemes. So mailto: call: sms: http: etc. So yeah, the QRCode will look different using the different ones listed because they will be using a different scheme and thus have a different QRCode generated. That being the case, it's not the job of this library to do that, but rather the end user to provide the correct data using a preferred scheme if needed.

**Comment by thatside** [comment]
I've checked it and I can agree now: text and url qr codes for one link starting with "http://" are the same. Closing the issue.
