### ISSUE TITLE
What about manual installation?

### ISSUE THREAD

**Issue by portapipe** [endroid/QrCode#52]
Not everyone use composer, so please add a manual installation guide, or at least a folder that we can drag&drop in our projects, thanks 😃

**Comment by endroid** [comment]
Hi @portapipe of course you can use the library without composer. However I wouldn't advise to do so because manual version management and autoloading are much more error prone. That's one of the reasons why it is not described in the readme.

Still, if you want to do this manually all you have to do is
1) get the project files from GitHub (either clone or download as ZIP)
2) make sure your autoloader looks in the right directories

Custom autoloading in PHP is a bit beyond the scope of this library but you can find many sources via Google regarding this topic.

Good luck!
