### ISSUE TITLE
CMYK setBackgroundColor

### ISSUE THREAD

**Issue by jon-rs** [endroid/QrCode#55]
Is there any support for CMYK or Spot color instead of RGB?

I believe this would be a huge help in the print industry.

**Comment by endroid** [comment]
Hi @jon-rs I don't think it is possible to convert the image to CMYK using GD. Starting from 2.0.22 GD supports loading CMYK images (so that should already work) but there is no method like Imagick::setColorspace to convert the resulting QR Code.

Maybe you can try to load the resulting image resource in ImageMagick and then convert the color space to achieve the desired result?
