### ISSUE TITLE
 failed to open stream

### ISSUE THREAD

**Issue by sm2017** [endroid/QrCode#71]
When we set a tiny text , QR code cannot be generated

```php
use Endroid\QrCode\QrCode;

$qrCode = new QrCode();
$qrCode
    ->setText('test')
    ->setSize(300)
    ->setPadding(10)
    ->setErrorCorrection('high')
    ->setForegroundColor(['r' => 0, 'g' => 0, 'b' => 0, 'a' => 0])
    ->setBackgroundColor(['r' => 255, 'g' => 255, 'b' => 255, 'a' => 0])
    ->setLabel('Scan the code')
    ->setLabelFontSize(16)
    ->setImageType(QrCode::IMAGE_TYPE_PNG)
;

// now we can directly output the qrcode
header('Content-Type: '.$qrCode->getContentType());
$qrCode->render();
```

Error is : 
```
Warning: fopen(vendor\endroid\qrcode\src/../assets/data/rsc0.dat): failed to open stream: No such file or directory in vendor\endroid\qrcode\src\QrCode.php on line 1130
```

**Comment by sm2017** [comment]
Any reply?

**Comment by endroid** [comment]
Hi @sm2017 sorry I am on a holiday at the moment so I can not check it but your code looks ok. I think fopen should be given an absolute path. You could try to see if it works when you pass the absolute path to the asset (I assume you already checked if the file exists).

Please let me know if that helps. Then I will fix it when I'm back. Or you can create a pull request if you have a fix that I can merge from here :)

**Comment by sm2017** [comment]
The problem is that there is no ```rsc0.dat``` file in ```data``` folder

**Comment by endroid** [comment]
Hi @sm2017 thank you for checking. I will see if I can reproduce and find a solution when I return home. If there is any progress in the meanwhile please let me know!

**Comment by sm2017** [comment]
Any updates?

**Comment by endroid** [comment]
Hi @sm2017 because of several reported issues with the underlying library I am currently switching to Bacon/BaconQrCode as the core library because it is more stable. Please try if you have the same issue when you install version 2.x. I have little knowledge of the script created by Swetake so unfortunately I have not found a solution for your problem with 1.x.

Please note that documentation is not yet up to date and some features like adding a logo or a label still need to be ported to the new version.
