### ISSUE TITLE
[BUG] Undefined offset: 85

### ISSUE THREAD

**Issue by temuri416** [endroid/QrCode#77]
Hi,

Thanks for the nice library!

The code below produces PHP warning `Undefined offset: 85` at this line:

https://github.com/endroid/QrCode/blob/master/src/QrCode.php#L1169

```php
$data = '{"i":"nata.gediobbi","v":1,"t":1,"d":"4AEPc9XuIQ0OjsZoSRWp9DRWlN6UyDvuMlyOYy8XjOw="}';
$qrCode = new Endroid\QrCode\QrCode;
$qrCode
    ->setText($data)
    ->setSize(150)
    ->setErrorCorrection('high')
    ->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
    ->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
    ->setPadding(30)
;
$qrCode->render('qrcode.png');
```

Any chance you could have a look?

Cheers!

**Comment by endroid** [comment]
Hi @temuri416 because of several reported issues with the underlying library I am currently switching to Bacon/BaconQrCode as the core library because it is more stable. Please try if you have the same issue when you install version 2.x. I have created a test containing the string you posted here and the QR decoders used in the tests is able to read the string correctly so I think it works.

I have little knowledge of the script created by Swetake so unfortunately I have not found a solution for your problem with 1.x. Please note that documentation is not yet up to date and some features like adding a logo or a label still need to be ported to the new version.

**Comment by temuri416** [comment]
I'll give it a try ASAP! Thanks.
