### ISSUE TITLE
quiet_zone=0 not working

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/QrCode#95]
When setting `quiet_zone: 0` in `config.yml`, I still get some whitespace included in the image (generated using the `DataUriWriter`). Is there a way to remove all whitespace/padding competely?

**Comment by endroid** [comment]
Hi @ThomasLandauer I noticed. However, this is an issue in https://github.com/Bacon/BaconQrCode so please mention it there. I plan on creating a padding or margin setting which you could abuse to remove this whitespace but I think it would best be solved in the core library instead of fixed afterwards.

**Comment by ThomasLandauer** [comment]
Thanks, see https://github.com/Bacon/BaconQrCode/issues/27

**Comment by ThomasLandauer** [comment]
They will not fix this! See https://github.com/Bacon/BaconQrCode/issues/26  
Please reopen.

**Comment by endroid** [comment]
That's unfortunate. Maybe they have good reasons to force inclusion of whitespace in these situations. If they are willing to provide a method for obtaining the amount of whitespace added easily I also think we should re-open this issue, although I still think that if this is really a bug or a missing feature this should be changed there in the instead of corrected afterwards in libraries that implement their generator.

**Comment by ThomasLandauer** [comment]
Well, according to the thread there, it doesn't look like they have good reasons - it looks more like a (unwanted?) side-effect of the implementation. The issue looks serious to me, since if you have multiple QR codes placed next to each other, you have no way to make them all the same size! - Take a look at the screenshot there.

I have way too little insight to suggest a solution. Why did you choose Bacon/BaconQrCode in the first place? What about including the suggested Imagick workaround right into your bundle?

**Comment by endroid** [comment]
I read over the Imagick solution and I think is worth a try so I'll re-open the issue and look at it soon. The reason I chose this library was that I needed a replacement for the one used in 1.x (which has no support whatsoever) and this looks like the most solid PHP QR code generation library that is still supported at the moment.

**Comment by DASPRiD** [comment]
Just chiming in here. The reason for the current state of the renderer is in fact an artefact resulting from the upstream source where BaconQrCode is coming from. It could definitely be refactored to allow fractional block sizes, but that could yield other problematic behaviours. For instance, right now, when a output size smaller than the block count is specified, it will automatically be raised so each block takes up at least one pixel. By removing all the integer constraints it could easily happen that non-readable QR codes are generated. One could argue that this would be in the responsibility of the developer using the library though.

Anyway, this thread and a prior issue made me thinking about refactoring the rendering architecture to solve this and a few older issues. That'll very likely require a major version bump though, except if I find a way to implement my wanted changes in a non BC breaking way.

**Comment by endroid** [comment]
Thank you for your input, sounds like a good reason. I think that the behavior expected by developers will be that the image has no added whitespace, but exactly the given size, even if this means that rounding issues occur. Maybe as a quick fix you can implement the Imagick solution you mentioned in the current version and make it available through an extra setting, for instance $renderer->setFullSize(true) which defaults to false so you introduce no BC breaks. Then in the next major version you could update the rendering logic so that the whitespace is not added.

Would this be possible as a short term solution?

**Comment by DASPRiD** [comment]
Not really; Right now, the PNG renderer is utilizing GD, which doesn't even support painting rectangles with fractional pixel sizes. Adding Imagick there would already be a BC break.

**Comment by endroid** [comment]
I understand. Then for now I will try to remove the whitespace on my side using Imagick. Please let me know (or update the issue on your side) when there is any progress regarding the whitespace issue.

Thanks again for the explanation.

**Comment by ThomasLandauer** [comment]
Well, finally I begin to understand what you guys are talking about :-)

May I suggest an ultra-short-term "solution": Include an explanation for this (at first glance) *weird* padding behavior in the docs, so people can at least understand that it's not a bug. Here's my suggestion (might not be accurate):

**Reason for "arbitrary" white-space being added as padding around the actual QR code inside the image:**  
Since it's not possible to draw "half"-pixels, the library first needs to calculate the number of black "dots" the QR code needs. This is then multiplied by 2,3,4,..., according to the desired overall size. The remaining space is filled with background color.  
Example: If the QR code needs 8 dots per line, and the desired size is 22, then the dots are multiplied by 2 (resulting in 16 being the actual size of the QR code), plus 3px padding on either side.

**Comment by DASPRiD** [comment]
Some good or bad news, depending on what you like to hear ;)

I've been looking through the code a little bit, and if I actually touch the library again, I'd upgrade it to PHP 7.1. This would be incompatible with your current library requirements though.

**Comment by endroid** [comment]
@ThomasLandauer Thank you, but having the issue mentioned here is enough. No real need to put things like this in the readme. Hope to have a fix soon.

@DASPRiD I will keep my library compliant with 5.6 for now, but of course you are free to determine your own requirements. If It conflicts with my minimum requirements I think I will stick with a workaround for now, NP ;)

**Comment by endroid** [comment]
Fixed in the lastest release.

**Comment by DASPRiD** [comment]
FYI: This is fixed with a new renderer in BaconQrCode 2.0.0.
